query SermonQuery($id: ID!) {
  node(id: $id) {
    ... on Sermon {
      id
      recordedAt
      title
      scriptureReading
      scriptureFocus
      speaker {
        id
        name
      }
      seriesIndex
      series {
        id
        name
        sermonsCount
      }
      audioUrl
      audioWaveformUrl
      duration
    }
  }
}
